language: scala
scala:
   - 2.11.6
env:
  - PLAY_VERSION=2.4.0
before_script:
  - wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/07b062b5d97c72b6b383
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: never