language: scala
scala:
   - 2.11.6
env:
  - ACTIVATOR_VERSION=1.3.4
before_script:
  - wget http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}.zip
  - unzip -q typesafe-activator-${ACTIVATOR_VERSION}.zip
script: typesafe-activator-${ACTIVATOR_VERSION}/activator test