language: scala
scala:
   - 2.11.6
jdk:
   - oraclejdk8
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/07b062b5d97c72b6b383
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: never
sudo: false
script:
  - sbt clean coverage test
after_success:
  - bash <(curl -s https://codecov.io/bash)