language: scala
scala:
   - 2.11.6
env:
  - ACTIVATOR_VERSION=1.3.4
before_script:
  - wget http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - unzip -q typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
script: typesafe-activator-${ACTIVATOR_VERSION}-minimal/activator test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/07b062b5d97c72b6b383
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: never